### ISSUE TITLE
Cannot remove stories in response to narrative

### ISSUE THREAD

**Issue by doctor-g** [stem-career-paths/game#2]
The new `conflict.gd` script in the RPG thread allows the player to choose to quit, but there's no way to actually remove rpg-related stories in response.

A good solution to this is to have a corresponding `remove_stories` function on `World` that will take out any stories from those available if they came from that directory. This can be done with TDD and then the corresponding call added to the `conflict.gd` scenario.

This allows us to add more stories to the RPG thread without narrative dissonance.

**Comment by squarepear** [comment]
Added in 00227f0c5c84c0b12305fec017ab74595b68aa1b
